### ISSUE TITLE
tcpdump -i eth0 imp6 not giving the right link local adressess

### ISSUE THREAD

**Issue by RSantelmo** [KatharaFramework/Kathara-Labs#24]
Greetings,

I'm a student in telecommunications and informatics and we're using kathara software to simulate a network with 7 routers, 3 servers and 1 host. We already configured all routers' interfaces and routing tables in IPv4 and IPv6 and everything was working fine. In the last lesson we were asked to execute the command (present on the subject) on node S2 and we should get at least one link local address of one of the servers linked directly, but I'm getting link local addresses that are not even present on any node of my simulated network. Although if I do ifconfig on my machine's terminal I can see that the link locals IPv6 returned inside kathara were there identified as veth713fee9d and kt-8eae47042334. But I don't even know what is the purpose of these interfaces. Another important point worth mentioning is that my colleagues that use fedora didn't have this issue at all, but to others with ubuntu and mint (like myself) it happened.

Any ideas on why this is happening?

Bellow it's attached the scheme of the simulated network.
![network](https://github.com/KatharaFramework/Kathara-Labs/assets/106079156/f01b3cce-7319-4bf1-8598-28ff8546ad9f)

Thank you in advance.
Best in advance,

Rui Passos

**Comment by lorenzo93** [comment]
Hi @RSantelmo ,

Thanks for opening the issue and sorry for the late reply, we were busy releasing a new version of Kathará :)
Your problem seems related to Kathará networking that creates "hidden" linux bridges (the ones starting with `kt-`) to manage the virtual collision domains. Those, behaving as bridges, probably interfere with the icmp traffic and gives you the wrong answer.
Probably, if you wait with the `tcpdump` command long enough you'll receive also the icmp packets of the servers.

We are aware that Kathará behaves slightly differently on Debian based (Ubuntu and Mint) and Red Hat based (Fedora) linux distributions, I think you've found another small difference.

Please add your lab (as a `.zip´ file) so that I can do some tests and provide you a more complete answer.

P.S. did you mispelled the `tcpdump` command in the title? If yes, can you fix the title?

**Comment by RSantelmo** [comment]
Hello Lorenzo!

Thank you so much for your answer and your will to help. Unfortunately I already had to deliver this part of the simulation for evaluation, so there's no need now.

All the best! :)

Rui Santelmo
