### ISSUE TITLE
FRR can't allocate memory

### ISSUE THREAD

**Issue by Aperence** [KatharaFramework/Kathara-Labs#31]
Hello,
While trying to run one of the [example lab](https://github.com/KatharaFramework/Kathara-Labs/tree/main/main-labs/intradomain-routing/frr/ospf/kathara-lab_ospf/kathara-lab_ospf_frr-singlearea), I encounter always the same error "fork() can't allocate memory" while trying to run `/etc/init.d/frr start`. 

![screenshot](https://github.com/KatharaFramework/Kathara-Labs/assets/78789735/1655bcff-86a2-4ffc-8f41-a7df86c7bba8)
Although, when checking the memory allowed to each device, I can see that they each have 15GB available, which should be more than enough to run frr.

![memory available](https://github.com/KatharaFramework/Kathara-Labs/assets/78789735/25f67ad9-3ff7-4b35-b487-46879509be06)

I thus wonder what am I doing wrong  ?
Thanks in advance for you help !

NB : my computer is running on fedora 38

**Comment by tcaiazzi** [comment]
Hi @Aperence, 

Thanks for opening the issue! 
 
To debug the problem I need further information:

- What OS are you using?
- Do you have the last version of Kathará? 

Thanks,
Tommaso

**Comment by Aperence** [comment]
Hi,

- My current docker version is 24.0.5 (see screen below for more details) 
![Screenshot from 2023-08-19 09-24-20](https://github.com/KatharaFramework/Kathara-Labs/assets/78789735/b383051d-3388-4f50-a79f-1d3ec843299b)

- I indeed have the latest version of kathara as I installed it 3 days ago (3.6.3) ![Screenshot from 2023-08-19 09-25-26](https://github.com/KatharaFramework/Kathara-Labs/assets/78789735/b4cdbde1-25ab-4b6c-b728-3c13fa62bf8a)

Thanks already for your help

**Comment by tcaiazzi** [comment]
Hi @Aperence, 

Sorry for the delay, I was on vacation until yesterday :innocent: 

I'm also experiencing your issue on my Fedora 38 VM. 

This is a very strange behavior since the error happens only with `frr`.  All the other daemons such as  `quagga`, `bind`, `apache2` work fine. 

Moreover, I found that if you use the `su` command, then `frr' starts correctly. 

![image](https://github.com/KatharaFramework/Kathara-Labs/assets/26346836/bbf4a081-83c0-47a4-8722-62f7b242d69c)

I think there is some differences in the environment of the two scenarios, and for some reason using `su` something (that allows `frr` to run properly) changes.

I'm still searching for a proper explanation. If you have some ideas let me know! 

Thanks!

**Comment by Aperence** [comment]
Hi,

Hope you had a good holiday !

This behaviour seems indeed really strange, and I don't really know what could be the cause of it, sadly. I'll inform you if I find any reason in the future, but it seems complicated

At least, thanks to your discovery with su, I can temporarily make a work-around by using:
```
su <<EOF
/etc/init.d/frr start
EOF
```

This isn't ideal, but well it kinda works for the moment at least 🙂

**Comment by lorenzo93** [comment]
Hi everyone,

@BuonHobo find the same bug in ArchLinux.
With the new Docker Images the `init.d` folder has been deprecated, so you need to use `systemctl`.
The new workaround for systemctl is:
```bash
su -c "systemctl start frr"
```

**Comment by tcaiazzi** [comment]
Hi @Aperence,

I'm closing this issue, since I opened a new one (KatharaFramework/Docker-Images#10) in the Docker images repository. We can continue the discussion there. 

Many thanks for the help and support :rocket:
