### ISSUE TITLE
Stp in Kathara

### ISSUE THREAD

**Issue by aletheia1995** [KatharaFramework/Kathara-Labs#5]
Good morning! I am trying two old Netkit labs in Kathara related to the bridging and stp. I am not able to make stp work properly. I have followed all the instructions carefully, I don't know what is going wrong. The machines exchange packets to determine who has to be the root bridge, but they remain stucked in that stage. Executing the brctl showstp <bridgename> command seems that all the switches pretends to be the root bridge. Do you have any suggestion on what is going on?
Thanks for your time,
Alessia

**Comment by lorenzo93** [comment]
Hi @aletheia1995 ,

unfortunatelly, not every Netkit lab is compatible with Kathará.
In your case, the STP protocol is unusable with Kathará because it uses linux bridges to create collision domain. Doing this, the linux bridges partecipate in the root bridge selection, creating problems in the STP instance of the Netkit lab.

I'm quite sure it is a problem impossible to solve unless you recompile the kernel or you modify docker in order to make the default linux bridges behave like a real hub.

**Comment by aletheia1995** [comment]
Ahn ok, I understand. Thank you very much.
